Repository AdaptiveConsulting/ReactiveTraderCloud, pull requests merged in 2019-05, with the labels that each got.

#1047 ARTP-547 - Initial prices on load are 0
  src/client/src/ui/spotTile/components/PriceButton/PriceButton.tsx
  src/client/src/ui/spotTile/components/PriceControls/PriceControls.tsx
  src/client/src/ui/spotTile/components/SpotTile.tsx
  src/client/src/ui/spotTile/components/stories/PriceButton.stories.tsx
  src/client/src/ui/spotTile/components/stories/SpotTile.stories.tsx
Labels: Waiting for approval, frontend

#1048 ARTP-619 - Firefox scrollbars
  src/client/src/shell/GlobalScrollbarStyle.tsx
  src/client/src/shell/routes/styled.tsx
  src/client/src/ui/analytics/components/styled.tsx
  src/client/src/ui/blotter/components/BlotterGrid.tsx
Labels: Waiting for approval, frontend

#1050 ReactiveTrader IOS PWA
  src/client/public/index.html
  src/client/public/manifest.json
  src/client/public/splashscreens/ipad_splash.png
  src/client/public/splashscreens/ipadpro1_splash.png
  src/client/public/splashscreens/ipadpro2_splash.png
  src/client/public/splashscreens/ipadpro3_splash.png
  src/client/public/splashscreens/iphone5_splash.png
  src/client/public/splashscreens/iphone6_splash.png
  src/client/public/splashscreens/iphoneplus_splash.png
  src/client/public/splashscreens/iphonex_splash.png
  src/client/public/splashscreens/iphonexr_splash.png
  src/client/public/splashscreens/iphonexsmax_splash.png
  src/client/public/touch-icon-iphone.png
  src/client/src/index.tsx
  src/client/src/rt-system/environment.ts
  src/client/src/rt-theme/globals.ts
  src/client/src/serviceWorker.js
  src/client/src/ui/analytics/AnalyticsContainer.tsx
  src/client/src/ui/blotter/BlotterContainer.tsx
  src/client/src/ui/spotTile/SpotTileContainer.tsx
  src/client/src/ui/workspace/workspaceHeader/styled.tsx
Labels: Waiting for approval, enhancement

#1052 Increase application disconnect time
  src/client/src/routes/MainRoute/MainRoute.tsx
Labels: Waiting for approval, frontend

#1054 ARTP-623 - Up the timeout from 15 minutes to 60 minutes
  src/client/src/routes/MainRoute/MainRoute.tsx
  src/client/src/routes/MainRoute/index.tsx
  src/client/src/shell/components/reconnect-modal/ReconnectModal.tsx
Labels: Waiting for approval, frontend

#1053 Fix FSBL platform check
  src/client/src/rt-components/platform/platform.ts
Labels: Waiting for approval, bug

#1056 ARTP-627 - Remove icon-popout title
  src/client/src/rt-components/icons/PopoutIcon.tsx
Labels: Waiting for approval

#1057 ARTP-636 - The Live Rates label, top left, should not be a clickable area
  src/client/src/ui/workspace/workspaceHeader/styled.tsx
Labels: Waiting for approval

#1058 ARTP-637 - Remove the central zero on the PnL tab range indicators
  src/client/src/ui/analytics/components/analyticsBarChart/PNLBar.tsx
  src/client/src/ui/analytics/components/analyticsBarChart/styled.tsx
Labels: Waiting for approval, frontend

#1059 ARTP-639 - The P & L tile loses its scroll bar when popped out
  src/client/src/rt-components/open-fin/OpenFinChrome.tsx
  src/client/src/rt-components/platform/externalWindowDefault.ts
  src/client/src/shell/routes/AnalyticsRoute.tsx
Labels: Waiting for approval, frontend

#1060 ARTP-634 - Remove the strange tooltip on the OpenFin logo, bottom right
  src/client/src/ui/status-bar/assets/OpenFinLogo.tsx
Labels: Waiting for approval, frontend

#1061 ARTP-631 - When any tile is popped out, you can select and copy text (you should not be able to do so)
  src/client/src/rt-components/open-fin/OpenFinChrome.tsx
Labels: Waiting for approval, frontend

#1062 ARTP-633 - On a popped tile, the x is too high, and not quite placed correctly
  src/client/src/rt-components/index.ts
  src/client/src/rt-components/open-fin/OpenFinChrome.tsx
  src/client/src/rt-components/open-fin/index.ts
  src/client/src/rt-components/platform/externalWindowDefault.ts
  src/client/src/shell/routes/AnalyticsRoute.tsx
  src/client/src/shell/routes/BlotterRoute.tsx
  src/client/src/ui/workspace/selectors.ts
Labels: Waiting for approval, frontend

#1049 ARTP-602 - Use React hooks in Reactive Analytics client
  src/client/src/rt-util/hooks/index.ts
  src/client/src/rt-util/hooks/useForceUpdate.ts
  src/client/src/rt-util/hooks/useWindowSize.ts
  src/client/src/rt-util/index.ts
  src/client/src/ui/analytics/components/Analytics.tsx
  src/client/src/ui/analytics/components/analyticsLineChart/AnalyticsLineChart.tsx
Labels: Waiting for approval, frontend

#1055 Fixed RFQ spread, add RFQ epic tests
  src/client/src/ui/spotTile/epics/combineSpotTileEpics.ts
  src/client/src/ui/spotTile/epics/rfqEpics.test.ts
  src/client/src/ui/spotTile/epics/rfqEpics.ts
Labels: Waiting for approval

#1063 ARTP-631 - When any tile is popped out, you can select and copy text (you should not be able to do so)
  src/client/src/rt-components/open-fin/OpenFinChrome.tsx
  src/client/src/rt-components/route-wrapper/RouteWrapper.tsx
Labels: Waiting for approval

#1065 ARTP-621 Add layouts service for demo to enable Snap and dock, tabbing... features
  src/client/public/config/openfin/demo.json
Labels: openfin

#1066 ARTP-638 - On hover of the amount in PnL tab range indicators, you should be able to see the precise amount
  src/client/src/ui/analytics/components/analyticsBarChart/PNLBar.tsx
  src/client/src/ui/analytics/components/analyticsBarChart/styled.tsx
Labels: Waiting for approval, frontend

#1067 ARTP-629 - The reject button on an RFQ overlaps slightly on the chartIQ button
  src/client/src/ui/spotTile/components/SpotTile.tsx
  src/client/src/ui/spotTile/components/Tile/Tile.tsx
  src/client/src/ui/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
  src/client/src/ui/spotTile/components/TileControls.tsx
  src/client/src/ui/spotTile/components/TileHeader.tsx
  src/client/src/ui/spotTile/components/TileSwitch.tsx
  src/client/src/ui/spotTile/components/stories/TileSwitch.stories.tsx
  src/client/src/ui/spotTile/components/styled.tsx
  src/client/src/ui/spotTile/components/types.ts
Labels: Waiting for approval, frontend

#1064 ARTP-635 - Clicking the OpenFin logo, bottom right, should go straight to the OpenFin website
  src/client/src/rt-components/index.ts
  src/client/src/rt-components/open-fin/OpenFinBrowserLink.tsx
  src/client/src/rt-components/open-fin/index.ts
  src/client/src/ui/status-bar/StatusBar.tsx
  src/client/src/ui/status-bar/styled.tsx
Labels: Waiting for approval, frontend

#1068 ARTP-621 Enable openfin services for all environments
  src/client/public/config/openfin/demo.json
  src/client/public/config/openfin/dev.json
  src/client/public/config/openfin/launcher-demo.json
  src/client/public/config/openfin/launcher-dev.json
  src/client/public/config/openfin/launcher-local.json
  src/client/public/config/openfin/local.json
Labels: openfin

#1071 ARTP-642 Openfin Cloud - Restore workspace
  src/client/src/routes/MainRoute/MainRoute.tsx
  src/client/src/rt-components/index.ts
  src/client/src/rt-components/platform/adapters/index.ts
  src/client/src/rt-components/platform/adapters/openfin/openFin.ts
  src/client/src/rt-components/platform/adapters/openfin/window.ts
  src/client/src/rt-components/platform/index.ts
  src/client/src/rt-components/tear-off/TearOff.tsx
  src/client/src/shell/index.ts
  src/client/src/shell/layouts/layoutActions.ts
  src/client/src/shell/layouts/reducer.ts
  src/client/src/shell/layouts/selectors.ts
  src/client/src/shell/routes/ShellRoute.tsx
  src/client/src/ui/blotter/epics/blotterServiceEpic.ts
  src/client/src/ui/workspace/Workspace.tsx
  src/client/src/ui/workspace/selectors.ts
Labels: openfin
