Repository AdaptiveConsulting/ReactiveTraderCloud, pull requests merged in 2019-04, with the labels that each got.

#1017 ARTP-524 / Ability to submit RFQ
  src/client/src/ui/spotTile/SpotTileContainer.tsx
  src/client/src/ui/spotTile/actions.ts
  src/client/src/ui/spotTile/components/PriceButton.tsx
  src/client/src/ui/spotTile/components/PriceButton/PriceButton.tsx
  src/client/src/ui/spotTile/components/PriceButton/index.tsx
  src/client/src/ui/spotTile/components/PriceButton/styled.tsx
  src/client/src/ui/spotTile/components/PriceControls.tsx
  src/client/src/ui/spotTile/components/PriceControls/PriceControls.tsx
  src/client/src/ui/spotTile/components/PriceControls/index.tsx
  src/client/src/ui/spotTile/components/PriceControls/styled.tsx
  src/client/src/ui/spotTile/components/RfqTimer.tsx
  src/client/src/ui/spotTile/components/SpotTile.tsx
  src/client/src/ui/spotTile/components/Tile.tsx
  src/client/src/ui/spotTile/components/TileBusinessLogic.ts
  src/client/src/ui/spotTile/components/TileSwitch.tsx
  src/client/src/ui/spotTile/components/analyticsTile/AnalyticsTile.tsx
  src/client/src/ui/spotTile/components/analyticsTile/AnalyticsTilePriceControl.tsx
  src/client/src/ui/spotTile/components/notifications/TileBooking.tsx
  src/client/src/ui/spotTile/components/notional/NotionalInput.tsx
  src/client/src/ui/spotTile/components/notional/styled.tsx
  src/client/src/ui/spotTile/components/stories/AnalyticsTitle.stories.tsx
  src/client/src/ui/spotTile/components/stories/NotionalInput.stories.tsx
  src/client/src/ui/spotTile/components/stories/SpotTile.stories.tsx
  src/client/src/ui/spotTile/components/stories/TileSwitch.stories.tsx
  src/client/src/ui/spotTile/components/styled.tsx
  src/client/src/ui/spotTile/components/test-resources/spotTileProps.ts
  src/client/src/ui/spotTile/components/types.ts
  src/client/src/ui/spotTile/epics/combineSpotTileEpics.ts
  src/client/src/ui/spotTile/epics/rfqTileEpics.ts
  src/client/src/ui/spotTile/model/rfqRequest.ts
  src/client/src/ui/spotTile/model/spotTileData.ts
  src/client/src/ui/spotTile/model/spotTileUtils.ts
  src/client/src/ui/spotTile/spotTileReducer.ts
Labels: Waiting for approval, frontend

#1027 ARTP-532 / Default amount for NZDUSD is now 10,000,000
  src/client/src/ui/spotTile/components/Tile.tsx
  src/client/src/ui/spotTile/components/TileBusinessLogic.ts
Labels: Waiting for approval, frontend

#1030 Export blotter to excel
  src/client/src/ui/blotter/components/Blotter.tsx
  src/client/src/ui/blotter/components/BlotterHeader.tsx
  src/client/src/ui/blotter/components/blotterUtils.ts
  src/client/src/ui/blotter/components/toolbar/ExcelButton.tsx
  src/client/src/ui/blotter/components/toolbar/ExcelLauncher.tsx
Labels: Waiting for approval

#1029 ARTP-573 / Tests and snapshots for Tile components
  src/client/__tests__/helpers/index.tsx
  src/client/src/ui/spotTile/components/Tile/Tile.test.tsx
  src/client/src/ui/spotTile/components/Tile/Tile.tsx
  src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.test.ts
  src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.ts
  src/client/src/ui/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
  src/client/src/ui/spotTile/components/Tile/index.tsx
  src/client/src/ui/spotTile/components/TileSwitch.tsx
  src/client/src/ui/spotTile/components/notional/NotionalInput.test.tsx
  src/client/src/ui/spotTile/components/notional/NotionalInput.tsx
  src/client/src/ui/spotTile/components/notional/__snapshots__/NotionalInput.test.tsx.snap
Labels: Waiting for approval, frontend

#1031 Artp 588/storybook analytics charts data
  src/client/src/ui/spotTile/components/test-resources/spotTileProps.ts
Labels: Waiting for approval, frontend

#1028 Excel legacy plugin
  src/client/public/plugin/README.md
  src/client/public/plugin/ReactiveTraderExcel.zip
  src/client/public/static/excel/instructions.html
  src/client/src/routes/SimpleLauncher/applicationConfigurations.tsx
  src/client/src/rt-components/platform/adapters/openfin/excel/README.md
  src/client/src/rt-components/platform/adapters/openfin/excel/index.ts
  src/client/src/rt-components/platform/adapters/openfin/excel/jsExcelAdapter.ts
  src/client/src/rt-components/platform/adapters/openfin/excel/legacyExcelAdapter.ts
  src/client/src/rt-components/platform/adapters/openfin/excel/types.ts
  src/client/src/rt-components/platform/adapters/openfin/openFin.ts
  src/client/src/rt-components/platform/adapters/types.ts
  src/client/src/ui/blotter/components/Blotter.tsx
  src/client/src/ui/blotter/components/BlotterHeader.tsx
  src/client/src/ui/blotter/components/blotterUtils.ts
  src/client/src/ui/blotter/components/toolbar/ExcelButton.tsx
  src/client/src/ui/blotter/components/toolbar/ExcelLauncher.tsx
  src/client/src/ui/spotTile/epics/closePositionEpic.ts
  src/client/src/ui/spotTile/epics/combineSpotTileEpics.ts
  src/client/src/ui/spotTile/epics/publishPriceUpdateEpic.ts
  src/client/src/ui/spotTile/epics/tradeExecutedEpic.ts
Labels: Waiting for approval, openfin

#1037 Artp 594/storybook loadable
  src/client/src/rt-components/loadable/Loadable.stories.tsx
  src/client/src/rt-components/loadable/Loadable.tsx
Labels: Waiting for approval, frontend

#1041 Artp 595/storybook trade notification
  src/client/package-lock.json
  src/client/src/shell/notification/TradeNotification.stories.tsx
  src/client/src/shell/notification/TradeNotification.tsx
  src/client/src/shell/notification/styled.tsx
Labels: Waiting for approval
