Repository AdaptiveConsulting/ReactiveTraderCloud, pull requests merged in 2021-03, with the labels that each got.

#1813 fix: window content height in Finsemble builds
  src/client/src/rt-platforms/finsemble/finsemble.ts
Labels: preview

#1846 chore(new-client): report ts errors from vite dev
  src/new-client/package-lock.json
  src/new-client/package.json
  src/new-client/vite.config.ts
Labels: size/XS

#1847 fix(new-client): Notional fixes (799 & 801)
  src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx
  src/new-client/src/App/LiveRates/Tile/Rfq/Rfq.state.ts
  src/new-client/src/App/LiveRates/Tile/Tile.state.ts
  src/new-client/src/App/LiveRates/Tile/Tile.test.tsx
Labels: size/L
